### ISSUE TITLE
Server error when querying /scim/v2/Users endpoint in production ColdFront

### ISSUE THREAD

**Issue by knikolla** [nerc-project/coldfront-plugin-api#37]
```
Unable to complete SCIM call.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/django_scim/views.py", line 112, in dispatch
    return super(SCIMView, self).dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/django_scim/views.py", line 292, in get
    return self.get_many(request)
  File "/opt/venv/lib/python3.9/site-packages/django_scim/views.py", line 315, in get_many
    qs = qs.order_by(self.lookup_field)
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1149, in order_by
    obj.query.add_ordering(*field_names)
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 2016, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1562, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'scim_id' into field. Choices are: allocationaccount, allocationadminnote, allocationuser, allocationusernote, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, project, projectadmincomment, projectuser, projectusermessage, researchoutput, resource, user_permissions, username, userprofile
Internal Server Error: /api/scim/v2/Users
```

**Comment by knikolla** [comment]
Is it perhaps because [this](https://github.com/nerc-project/coldfront-plugin-api/blob/2e68d39374168b95b0c5d925ce1ab78d3894f3c8/src/local_settings.py#L31) is missing from [here](https://github.com/nerc-project/coldfront-nerc/blob/main/src/local_settings.py)?

**Comment by QuanMPhm** [comment]
@knikolla I am assuming that might be part of the problem. Right now I'm trying to run nerc-coldfront locally on my VM. I'll get back to this soon.

**Comment by QuanMPhm** [comment]
@knikolla From my testing, it seems you're right. The settings for the `django_scim` module is placed in `local_settings.py`, not `config.py` for `coldfront-plugin-api`, which would mean the settings for `django_scim` was not imported into `nerc_coldfront`, and explains the error you got.

We could either place the settings for `django_scim` in `config.py` for `coldfront-plugin-api`, or copy it into `local_settings.py` of `nerc_coldfront`, as you suggested. I think it makes more sense to put the settings in `config.py`, since this would maintain a single source of truth for the `django_scim` settings.
